p1 = int(input("Insira a nota da avaliação p1: "))
p2 = int(input("Insira a nota da avaliação p2: ")) 
pi = int(input("Insira nota do Projeto integrador: "))
MF = (0.3 * p1 + 0.5 * p2 + 0.2 * pi)
print(f"Sua Média final será:, {MF}")
